### ISSUE TITLE
Genome index build memory issue

### ISSUE THREAD

**Issue by mkatsanto** [iraiosub/riboseq-flow#84]
Hello and thanks for the nice workflow! I am trying to execute riboseq-flow on some mouse data with the command 
`nextflow run iraiosub/riboseq-flow -r v1.1.1 -profile singularity -resume --input samplesheet.csv --fasta /scicore/home/zavolan/katsanto/PROJECTS/ribosome_profiling/riboseq_benchmark/ready_workflows/riboseq_pipeline/snakemake/annotation/Mus_musculus.GRCm39.cdna.all.fa --gtf /scicore/home/zavolan/katsanto/PROJECTS/ribosome_profiling/riboseq_benchmark/ready_workflows/riboseq_pipeline/snakemake/annotation/Mus_musculus.GRCm39.112.gtf --contaminants_fasta /scicore/home/zavolan/katsanto/PROJECTS/ribosome_profiling/riboseq_benchmark/ready_workflows/riboseq_pipeline/snakemake/annotation/rRNA_mus_musculus.fasta --strandedness forward  --skip_umi_extract`

and got the error:
 EXITING because of FATAL PARAMETER ERROR: limitGenomeGenerateRAM=31000000000is too small for your genome
  SOLUTION: please specify --limitGenomeGenerateRAM not less than 81081488992 and make that much RAM available

  Jun 13 16:08:15 ...... FATAL ERROR, exiting
  
  
  Tried to adjust that with :
  
  nextflow run iraiosub/riboseq-flow -r v1.1.1 -profile singularity -resume --input samplesheet.csv --fasta /scicore/home/zavolan/katsanto/PROJECTS/ribosome_profiling/riboseq_benchmark/ready_workflows/riboseq_pipeline/snakemake/annotation/Mus_musculus.GRCm39.cdna.all.fa --gtf /scicore/home/zavolan/katsanto/PROJECTS/ribosome_profiling/riboseq_benchmark/ready_workflows/riboseq_pipeline/snakemake/annotation/Mus_musculus.GRCm39.112.gtf --contaminants_fasta /scicore/home/zavolan/katsanto/PROJECTS/ribosome_profiling/riboseq_benchmark/ready_workflows/riboseq_pipeline/snakemake/annotation/rRNA_mus_musculus.fasta --strandedness forward --star_args limitGenomeGenerateRAM=81081488992 --skip_umi_extract
  
 But it does not work. Is there any other  option available I maybe missed?
 
 Thanks

**Comment by iraiosub** [comment]
Hi Maria, any luck getting this to work? I will close the issue as solved for now. You are welcome to re-open if you're still encountering problems.

**Comment by mkatsanto** [comment]
Thank you for the help, yes I managed to get the workflow running.
