### ISSUE TITLE
ERROR: unrecognized parameter name "quantTranscriptomeBan" in input "Command-Line-Initial"

### ISSUE THREAD

**Issue by huipan1973** [iraiosub/riboseq-flow#85]
After installing Riboseq-flow, I ran the test using the following command

nextflow run iraiosub/riboseq-flow -r v1.1.1 -profile test, singularity

But I got the error during mapping.

Jun-19 17:54:31.687 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'RIBOSEQ:MAP (test_data)'

Caused by:
  Process `RIBOSEQ:MAP (test_data)` terminated with an error exit status (102)

Command executed:

  STAR --runThreadN 1     --genomeDir star     --readFilesIn test_data.unmapped.fastq.gz     --outFileNamePrefix test_data.     --readFilesCommand zcat --outSAMtype BAM SortedByCoordinate --seedSearchStartLmax 15 --outReadsUnmapped Fastx --genomeLoad NoSharedMemory --outFilterMultimapNmax 1 --outFilterMismatchNoverReadLmax 0.08 --alignEndsType EndToEnd --quantMode TranscriptomeSAM --outSAMattributes Standard --quantTranscriptomeBan Singleend
  
  samtools index -@ 1 test_data.Aligned.sortedByCoord.out.bam
  
  samtools sort -@ 1 test_data.Aligned.toTranscriptome.out.bam > test_data.Aligned.toTranscriptome.sorted.out.bam
  samtools index -@ 1 test_data.Aligned.toTranscriptome.sorted.out.bam

Command exit status:
  102

Command output:
  (empty)

Command error:
  
  EXITING: FATAL INPUT ERROR: unrecognized parameter name "quantTranscriptomeBan" in input "Command-Line-Initial"
  SOLUTION: use correct parameter name (check the manual)
  
  Jun 19 17:54:31 ...... FATAL ERROR, exiting

**Comment by iraiosub** [comment]
hi Hui, thanks for trying out riboseq-flow.

I noticed that there is a space between test and singularity. it should be `-profile test,singularity`. Can you check and let me know if the error is still occuring after fixing the run command? 

I also could not reproduce the error, with or without the extra space. Could you please share the following information:

1. are you using a local machine or an HPC system?
2. what is your OS and system specifications?
3. what versions of Java, Nextflow and Singularity have you used?

**Comment by huipan1973** [comment]
Hi, I actually figured out that was because the incompatible version of STAR aligner.
I found out that "The --quantTranscriptomeSAMoutput option was introduced in STAR 2.7.11b. It replaces the previous --quantTranscriptomeBan parameter and provides more explicit naming of options."

After I downgraded STAR from 2.7.11b to 2.7.11a, I fixed the error.

**Comment by iraiosub** [comment]
Hi Hui - riboseq-flow is fully containerised, so if Singularity worked correctly on your system, the correct STAR version deployed with the pipeline (2.7.10) should have been used. There is a chance that your system configuration is set up in such a way that your local software versions are used in some cases instead of the ones from the containers. Although the pipeline might run, it seems to be using your locally installed software, which isn't good for reproducibility.  I hope this makes sense. I will now mark this issue as closed.

**Comment by huipan1973** [comment]
Yes, after reconfiguring Singularity. It is working as expected.
