### ISSUE TITLE
Add functions to extract UMI at the 3' end of reads

### ISSUE THREAD

**Issue by huipan1973** [iraiosub/riboseq-flow#86]
Is there an option to extract UMI at the 3' end of reads? Could you add that function?

**Comment by huipan1973** [comment]
It looks like the pipeline performs UMI extraction before adaptor trimming. Our 3' UMI is upstream of the 3' adapter. Is there a way to trim the adapter and then extract the UMI?

**Comment by iraiosub** [comment]
If your read design is insert-UMI-adaptor, where the UMI is located before the adaptor sequence, you can still use riboseq-flow (which uses UMI-tools) to extract the UMI and move it to the header without removing the adaptor, and only then trim the adaptor.  

You can achieve this by providing the right options for UMI-tools in riboseq-flow: i.e. `--umi_extract_method` (equivalent to `--extract-method` in UMI-tools) as 'regex'  and `--umi_pattern `(equivalent to `--bc-pattern` in UMI-tools) as the regular expression fit for your read structure and aim. You need to go to the UMI-tools documentation to figure out the settings and expression appropriate for your case.  

As this functionality is already supported by riboseq-flow, I will now close this issue.

**Comment by huipan1973** [comment]
Hi,

Yes, I am aware of the regex option. The problem is that cutadapt was run after umi_tools. Therefore, umi_tools will extract part of the adapter instead of the UMI which is upstream of the adapter.
We have used other pipeline that runs adapter trimming before umi_tools extract, we are thinking if you could make such modification to Riboseq-flow.

Best regards,
Hui

**Comment by iraiosub** [comment]
Hi Hui,

if you provide the correct regex to UMI-tools to make sure the adaptor is retained in the reads during the process, you can first extract the UMIs and and then do adaptor trimming, without the need to swap the order of these steps in riboseq-flow. We implement UMI extraction before adaptor trimming for technical reasons. Since the pipeline works with your library design as it is, we will not modify the workflow to accommodate this use case.

**Comment by huipan1973** [comment]
I will need to add the adapter sequence to the regex pattern with some mismatch allowed, it that right?

Best regards,
Hui
